### PR TITLE
Add a pyviz_extension baseclass for other projects

### PR DESCRIPTION
**Pull request by philippjfr**
Both holoviews and panel would subclass this extension and register delete actions.

- [x] Closes https://github.com/pyviz/pyviz_comms/issues/16

### CODE REVIEW

**Comment by jbednar** [comment]
But an app will still need to run both the hv and pn extensions if it uses both, in order for the relevant items from that library to get deleted?

**Comment by philippjfr** [comment]
>But an app will still need to run both the hv and pn extensions if it uses both, in order for the relevant items from that library to get deleted?

No, the delete hooks are registered independently of which one you call. If you are using any holoviews components you should call the holoviews extension though mainly to ensure that the bokeh backend is set as the default.

**Comment by jbednar** [comment]
Ok, sounds good.

**Comment by philippjfr** [comment]
I've now added PRs in holoviews and panel to make use of this extension which will have to wait on this PR to be merged and a new pyviz_comms release to be available.

**Comment by philippjfr** [comment]
To be totally clear, an app has never had to call both extensions, this is all for the notebook.

**Comment by jlstevens** [comment]
Looks good. All that we need to do now is document that people using holoviews always just need `hv.extension` (whether or not they use panel) and everyone else needs `pn.extension`. We discussed this and decided that this can be documented in two places:

* In panel wherever holoviews is discussed.
* In holoviews when panel is introduced for building dashboards.

As the code here looks good, I'll go ahead and merge.

**Pull request merged**
