### PR TITLE
Compatibility with JupyterLab 0.34.x

### PR DESCRIPTION
**Pull request by stonebig**
try to resolve https://github.com/pyviz/pyviz_comms/issues/9

### CODE REVIEW

**Comment by philippjfr** [comment]
Won't have much time for testing this today, but if you tell me that bumping the versions is enough I'll trust you :-)

**Comment by stonebig** [comment]
I just applies blindly the recommandation @blink1073, the guy who knows, and I can confirm you current state is not ok for Jupyterlab-0.34.

**Comment by philippjfr** [comment]
> I can confirm you current state is not ok for Jupyterlab-0.34.

So you're saying this PR is **not** sufficient?

**Comment by stonebig** [comment]
I say previous pyviz_comms is not working with Jupyterlab-0.34 , and the doctor said this https://github.com/jupyterlab/jupyterlab/issues/5155#issuecomment-414052583

**Comment by philippjfr** [comment]
Thanks, merging and releasing.

**Comment by philippjfr** [comment]
Version 0.6.1 of the extension should now be available on npm.

**Comment by stonebig** [comment]
thanks, trying immediatly.

**Comment by stonebig** [comment]
i see Warning messages around a mysterious browserslist....  still yarn-ing ...

````
C:\WinP\bd36\buQt5\winp64-3.6.x.2\scripts>"%WINPYDIR%\Scripts\jupyter.exe" labextension install  @pyviz/jupyterlab_pyviz
> C:\WinP\bd36\buQt5\winp64-3.6.x.2\python-3.6.6.amd64\..\t\n\npm.CMD pack @pyviz/jupyterlab_pyviz
pyviz-jupyterlab_pyviz-0.6.1.tgz
> node C:\WinP\bd36\buQt5\winp64-3.6.x.2\python-3.6.6.amd64\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
⠐ uglifyjs-webpack-plugin@~1.2.5
````

**Pull request merged**
