### PR TITLE
phosphor/coreutils max version is 1.3.0

### PR DESCRIPTION
**Pull request by stonebig**

### CODE REVIEW

**Comment by philippjfr** [comment]
Does this mean the 0.6.2 package I published is currently broken?

**Comment by stonebig** [comment]
yes
phosphor/coreutils max version is 1.3.0
image

**Comment by philippjfr** [comment]
Okay, thanks, I'll push another release. Should have tried it before publishing I suppose ;-)

**Comment by stonebig** [comment]
argh, I didn't upgrade version to 0.6.3, maybe it needs to be done ?

**Comment by philippjfr** [comment]
I'll do that before I publish.

**Comment by stonebig** [comment]
sorry for the mistake.

**Comment by stonebig** [comment]
so, after choosing by hand the pohsphor/coreutils-1.3.0, holoviews works on Jupyterlab-0.35.

**Comment by stonebig** [comment]
image

**Comment by philippjfr** [comment]
Great, 0.6.3 is also released on npm now. Thanks for all your efforts.

**Pull request merged**
